name: crm-system
services:
  crm-system:
    image: ${IMAGE_NAME}
    hostname: crm-system
    container_name: crm-system
    ports:
      - "8081:8081"
    networks:
      - vps-network
    env_file:
      - ../${ENV}local.env
    volumes:
      - ${FILES_STORAGE_DIRECTORY}:/opt/crm-system/files_storage_directory

networks:
  vps-network:
    name: vps-network
    driver: bridge
